name: dpc
description: A simple nom-like parser combinator library
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
